### ISSUE TITLE
Which should I follow:

### ISSUE THREAD

**Issue by JoaoAlexNunes** [ALT-F4-LLC/kickstart.nix#41]
This is more a question/suggestion then a issue, if I'm in Debian which guide should I follow?

**Comment by erikreinert** [comment]
Anything not `macOS` or `NixOS` can use the Home Manager setup: https://github.com/ALT-F4-LLC/kickstart.nix?tab=readme-ov-file#setup-home-manager

We can probably make that a bit clearer in the docs. I'll make a ticket!
