### ISSUE TITLE
Update Home Manager Guide

### ISSUE THREAD

**Issue by erikreinert** [ALT-F4-LLC/kickstart.nix#42]
## Changes

Improvements:

- make sure it clearly states that this is for anything not using `nix-darwin` or `nixos`

This comes from #41 which was brought up as a question as to which template to use.

**Comment by JoaoAlexNunes** [comment]
in addition is there a way that ```homeDirectory = throw "<enter homeDirectory in flake.nix>"; # TODO: home directory of the user``` could be more clear

**Comment by hbjydev** [comment]
> in addition is there a way that `homeDirectory = throw "<enter homeDirectory in flake.nix>"; # TODO: home directory of the user` could be more clear
> 
> because there i really dont know what to put

So what you'd put would be the path to your home directory, like the comment says -- something like `/home/joaoalexnunes`. On Linux, that's usually gonna be `/home/<your username>`, and on macOS it'll be `/Users/<your username>`.

**Comment by erikreinert** [comment]
Got all these in #47! Thank you!
