### ISSUE TITLE
nixpkgs.hostPlatform defaults to aarch64-linux

### ISSUE THREAD

**Issue by hbjydev** [ALT-F4-LLC/kickstart.nix#8]
https://github.com/ALT-F4-LLC/kickstart.nix/blob/c6335d1565f062f4af17987cd1b64c812685e0c9/system/nixos-hardware-configuration.nix#L35

Should this not be x86_64-linux as a default? It's the more usual Linux arch

**Comment by erikreinert** [comment]
Yeah we need to pass the param down in the function.

**Comment by PhilTaken** [comment]
I would suggest moving this into modules/configuration.nix and passing the system as an argument instead of hardcoding it

**Comment by erikreinert** [comment]
This has been fixed!
